[build-system]
requires = [
  "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "Code-Pile"
requires-python = ">=3.9"
version = "0.0.1"
dependencies = [
    "pydantic",
    "internetarchive",
    "xmltodict",
    "simplejson",
    "pandas",
    "py7zr",
    "pyarrow"
]
